name: ci
on:
  pull_request:
    branches:
      - master
      - development

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8.0.0
      - name: Run tests
        run: lua ./testRunner.lua
        working-directory: ./testing